#!/bin/sh

set -e

case "$1" in
    purge|remove|failed-upgrade|abort-install|abort-upgrade|disappear)
	if [ -L /usr/share/mythtv/themes/Neuros-Wide ]
	then
	    rm -f /usr/share/mythtv/themes/Neuros-Wide
	fi
    ;;
esac

#DEBHELPER#

exit 0


